src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amount_Claimed_by_Organisation__c</fullName>
        <label>Total Amount Claimed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Remaining_by_Organisation__c</fullName>
        <label>Amount Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Requested_by_Organisation__c</fullName>
        <label>Total Approved Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Nissan Dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Associated_Product__c.object
<CustomObject>
    <label>Associated Product</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Assistance__c.object
<CustomObject>
    <fields>
        <fullName>Vehicles_Claimed__c</fullName>
        <inlineHelpText>Number of retailed vehicles against this Special Assistance request.</inlineHelpText>
        <label>Vehicles Claimed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Special Assistance</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Special Assistance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Assistance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestRetailedVehiclesTriggers.cls
@isTest
private class TestRetailedVehiclesTriggers {

	static Id orgId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organisation').getRecordTypeId();
   	static Id dealerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();  

    static testMethod void TestRetailedVehiclesBeforeAndAfterInsert() {
    	List<Account> Organisation = new List<Account>();
        List<Special_Assistance__c> sas = TestDataProvider.createSpecialAssistance(50, Organisation);
        List<Product2> products = new List<Product2>();
        List<Associated_Product__c> associatedProducts = new List<Associated_Product__c>();
        List<Contract> contracts = TestDataProvider.createContracts(Organisation, products, associatedProducts);
        Test.startTest();
        TestDataProvider.createRetailedVehicles(sas, Organisation, products);
        Test.stopTest();
        
        for(Special_Assistance__c sa : [Select Vehicles_Claimed__c from Special_Assistance__c]) {
            system.assert(sa.Vehicles_Claimed__c ==15);
        }
        for(Account a : [Select Amount_Claimed_by_Organisation__c, Amount_Remaining_by_Organisation__c, Amount_Requested_by_Organisation__c from Account where Id = :orgId]) {
            system.assertNotEquals(a.Amount_Claimed_by_Organisation__c,0);
            system.assertNotEquals(a.Amount_Remaining_by_Organisation__c,0);
        }
    }
}