src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Eastern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTS FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEHICLES FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTS &amp; VEHICLE FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CURRENT DEALER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEASED TRADING</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Model__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Models</relationshipLabel>
        <relationshipName>Campaign_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Campaign Models</relationshipLabel>
        <relationshipName>Campaign_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Model</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Campaign Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter a Contact with a valid email</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation_Vehicle__c</fullName>
        <label>Evaluation Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Evaluation vehicle with Live status</errorMessage>
            <filterItems>
                <field>Evaluation_Vehicle__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Grounded</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Evaluation_Vehicle__c</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <label>Organisation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Evaluation_Vehicle__r.Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Evaluation_Vehicle__r.Status__c )</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Evaluation Vehicles</relationshipLabel>
        <relationshipName>Evaluation_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Head Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SUO__c</fullName>
        <label>SUO</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grounded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grounded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select vehicles with SFDC Product Level 1</errorMessage>
            <filterItems>
                <field>Product2.SFDC_Product_Level__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Evaluation Vehicles</relationshipLabel>
        <relationshipName>Evaluation_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation Vehicle</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Nissan_Fleet_Vehicles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Nissan Fleet Vehicles</label>
</CustomObject>

src/objects/Retailed_Vehicles__c.object
<CustomObject>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text(Dealer__r.Region__c )</formula>
        <inlineHelpText>Dealer&apos;s region</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailed_Date__c</fullName>
        <label>Retailed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailed Vehicle</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Retailed Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailed Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Result__c.object
<CustomObject>
    <description>Store all the anwers of the booking survey</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluation_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation Booking</label>
        <referenceTo>Evaluation_Booking__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataUtility.cls
/**
    *This class contains the creation of test data for the test classes
    *@author Kim Noceda - Proquest IT
    *@version 1.0 Created 10/13/2014
**/
public with sharing class TestDataUtility {
    
    //CREATE ACCOUNT
    public static List<Account> createAccounts(integer numberOfAccounts, String recordTypeName){
        Id recordTypeId = [Select Id from RecordType where SObjectType =: 'Account' AND DeveloperName =: recordTypeName LIMIT 1].Id;
        List<Account> accounts = new List<Account>();
        for(Integer i = 0; i < numberOfAccounts; i++){
            Account account = new Account();
            account.RecordTypeId = recordTypeId;
            account.Name = 'TestOrganisationName';
            
            accounts.add(account);
        }
        
        return accounts;
    }
    
    //CREATE CONTACT
    public static List<Contact> createContacts(integer numberOfContact, List<Account> accounts){
        List<Contact> contacts = new List<Contact>();
        for(Integer i = 0; i < numberOfContact; i++){
            Contact contact = new Contact();
            contact.AccountId = accounts.get(0).Id;
            contact.FirstName = 'TestFirstName';
            contact.LastName = 'TestLastName';
            contact.Email = 'testemail@test.com';
            contacts.add(contact);
        }
        
        return contacts;
    }
    
    //CREATE EVALUATION VEHICLE
    public static List<Evaluation_Vehicle__c> createEvaluationVehicle(integer numberOfVehicles, Product2 product){
    	List<Evaluation_Vehicle__c> evalVehicles = new List<Evaluation_Vehicle__c>();
    	 for(Integer i = 0; i < numberOfVehicles; i++){
            Evaluation_Vehicle__c evalVehicle = new Evaluation_Vehicle__c();
            evalVehicle.Vehicle__c = product.Id;
            evalVehicle.Status__c = 'Live';
            evalVehicle.SUO__c = '000000';
            evalVehicle.Region__c = 'Northern';
            
            evalVehicles.add(evalVehicle);
        }
        
        return evalVehicles;
    }
    
    //CREATE EVALUATION BOOKING
    public static List<Evaluation_Booking__c> createEvaluationBooking(integer numberOfBookings, List<Evaluation_Vehicle__c> evalVehicles, List<Contact> contact){
    	List<Evaluation_Booking__c> evalBookings = new List<Evaluation_Booking__c>();
    	 for(Integer i = 0; i < numberOfBookings; i++){
            Evaluation_Booking__c evalBooking = new Evaluation_Booking__c();
            evalBooking.Evaluation_Vehicle__c = evalVehicles.get(0).Id;
            evalBooking.Contact__c = contact.get(0).Id;
            evalBooking.Start_Date__c = Date.Today();
            evalBooking.End_Date__c = Date.Today().addDays(20);
            
            evalBookings.add(evalBooking);
        }
        
        return evalBookings;
    }
    
    //CREATE EVALUATION BOOKING2
    public static List<Evaluation_Booking__c> createEvaluationBooking2(integer numberOfBookings, List<Evaluation_Vehicle__c> evalVehicles, List<Contact> contact){
    	List<Evaluation_Booking__c> evalBookings = new List<Evaluation_Booking__c>();
    	 for(Integer i = 1; i <= numberOfBookings; i++){
            Evaluation_Booking__c evalBooking = new Evaluation_Booking__c();
            evalBooking.Evaluation_Vehicle__c = evalVehicles.get(0).Id;
            evalBooking.Contact__c = contact.get(0).Id;
            evalBooking.Start_Date__c = Date.newInstance(Date.Today().year(),i,1);
            evalBooking.End_Date__c = Date.Today().addDays(10);
            
            evalBookings.add(evalBooking);
        }
        
        return evalBookings;
    }
    
    //CREATE SURVEY RESULTS
    public static List<Survey_Result__c> createSurveyResult(integer numberOfSurveys, List<Contact> contacts, List<Evaluation_Booking__c> evalBookings){
    	List<Survey_Result__c> surveyResults = new List<Survey_Result__c>();
    	for(Integer i = 1; i <= numberOfSurveys; i++){
            Survey_Result__c surveyResult = new Survey_Result__c();
            surveyResult.Contact__c = contacts.get(0).Id;
            surveyResult.Evaluation_Booking__c = evalBookings.get(0).Id;
            
            surveyResults.add(surveyResult);
        }
        
        return surveyResults;
    }
    
    //CREATE CAMPAIGN
    public static List<Campaign> createCampaigns(integer numberOfCampaigns){
    	List<Campaign> campaigns = new List<Campaign>();
    	for(integer i = 0; i <= numberOfCampaigns; i++){
    		Campaign campaign = new Campaign();
    		campaign.Name = 'TestCampaign'+i;
    		campaign.StartDate = Date.Today().addDays(-30);
    		campaign.EndDate = Date.Today().addDays(30);
    		
    		campaigns.add(campaign);
    	}
    	
    	return campaigns;
    }
    
    //CREATE RETAILED VEHICLES
    public static List<Retailed_Vehicles__c> createRetailedVehicles(integer numberOfRetailedVehicles, List<Account> organisations, Product2 product){
    	List<Retailed_Vehicles__c> retailedVehicles = new List<Retailed_Vehicles__c>();
    	for(integer i = 0;i < numberOfRetailedVehicles; i++){
    		Retailed_Vehicles__c retailedVehicle = new Retailed_Vehicles__c();
    		retailedVehicle.Organisation__c = organisations.get(0).Id;
    		retailedVehicle.Vehicle__c = product.Id;
    		retailedVehicle.Retailed_Date__c = Date.Today();
    		
    		retailedVehicles.add(retailedVehicle);
    	}
    	
    	return retailedVehicles;
    }
    
    //CREATE CAMPAIGN MODELS
    public static List<Campaign_Model__c> createCampaignModel(integer numberOfCampaignModels, List<Campaign> campaigns, Product2 vehicle){
    	List<Campaign_Model__c> campaignModels = new List<Campaign_Model__c>();
    	for(integer i = 0; i < numberOfCampaignModels;i++){
    		Campaign_Model__c campaignModel = new Campaign_Model__c();
    		campaignModel.Campaign__c = campaigns.get(0).Id;
    		campaignModel.Vehicle__c = vehicle.Id;
    		
    		campaignModels.add(campaignModel);
    	}
    	
    	return campaignModels;
    }
    
    //CREATE FLEET VEHICLES
    public static List<Nissan_Fleet_Vehicles__c> createFleetVehicles(integer numberOfFleetVehicles){
    	List<Nissan_Fleet_Vehicles__c> fleetVehicles = new List<Nissan_Fleet_Vehicles__c>();
    	for(integer i = 0; i < numberOfFleetVehicles;i++){
    		Nissan_Fleet_Vehicles__c fleetVehicle = new Nissan_Fleet_Vehicles__c();
    		fleetVehicle.Name = 'testFleetVehicle'+i;
    		
    		fleetVehicles.add(fleetVehicle);
    	}
    	
    	return fleetVehicles;
    }
}