src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Model__c.object
<CustomObject>
    <label>Campaign Model</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Campaign Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SFDC_Product_Level__c</fullName>
        <inlineHelpText>Indicated which level in the product hierarchy this product sit</inlineHelpText>
        <label>SFDC Product Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Retailed_Vehicles__c.object
<CustomObject>
    <fields>
        <fullName>Retailed_Date__c</fullName>
        <label>Retailed Date</label>
        <type>Date</type>
    </fields>
    <label>Retailed Vehicle</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Retailed Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailed Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateCampaignSalesTest.cls
@isTest(SeeAllData=true)
private class CreateCampaignSalesTest {

	static testmethod void testInsertCampaignModels1(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Campaign> campaigns = TestDataUtility.createCampaigns(1);
		insert campaigns;
		
		List<Campaign_Model__c> campaignModels = TestDataUtility.createCampaignModel(1, campaigns, vehicle);
		insert campaignModels;
		
		Test.startTest();	
			List<Retailed_Vehicles__c> retailedVehicles = TestDataUtility.createRetailedVehicles(1,accounts,vehicle);
			insert retailedVehicles;
		Test.stopTest();
	}
	
	static testmethod void testInsertCampaignModels2(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Campaign> campaigns = TestDataUtility.createCampaigns(1);
		campaigns.get(0).StartDate = Date.Today().addDays(-90);
		campaigns.get(0).EndDate = Date.Today().addDays(-60);
		insert campaigns;
		
		List<Campaign_Model__c> campaignModels = TestDataUtility.createCampaignModel(1, campaigns, vehicle);
		insert campaignModels;
		
		Test.startTest();	
			List<Retailed_Vehicles__c> retailedVehicles = TestDataUtility.createRetailedVehicles(2,accounts,vehicle);
			retailedVehicles.get(0).Retailed_Date__c = Date.Today().addDays(-360);
			insert retailedVehicles;
		Test.stopTest();
	}
	
	static testmethod void testInsertCampaignModels3(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Campaign> campaigns = TestDataUtility.createCampaigns(1);
		insert campaigns;
		
		List<Campaign_Model__c> campaignModels = TestDataUtility.createCampaignModel(1, campaigns, vehicle);
		insert campaignModels;
		
		List<Retailed_Vehicles__c> retailedVehicles = TestDataUtility.createRetailedVehicles(2,accounts,vehicle);
		retailedVehicles.get(0).Retailed_Date__c = Date.Today().addDays(-100);
		insert retailedVehicles;
		
		Test.startTest();	
			List<Retailed_Vehicles__c> retailedVehicles2 = TestDataUtility.createRetailedVehicles(1,accounts,vehicle);
			retailedVehicles2.get(0).Retailed_Date__c = Date.Today().addDays(-45);
			insert retailedVehicles2;
		Test.stopTest();
	}
}