src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_a_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has a Contract?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTS FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEHICLES FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTS &amp; VEHICLE FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CURRENT DEALER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEASED TRADING</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Nissan Dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Associated_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Associated Products</relationshipLabel>
        <relationshipName>Associated_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Associated Products</relationshipLabel>
        <relationshipName>Associated_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Product</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Delivery Schedules (Dealer)</relationshipLabel>
        <relationshipName>Delivery_Schedule_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Delivery Schedules (Organisation)</relationshipLabel>
        <relationshipName>Delivery_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Month__c</fullName>
        <label>Reporting Month</label>
        <referenceTo>Reporting_Month__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Delivery Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Special_Assistance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Searches for Special Assistance related to this Organisation.</inlineHelpText>
        <label>Special Assistance</label>
        <referenceTo>Special_Assistance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reporting_Month__c.object
<CustomObject>
    <label>Reporting Month</label>
    <nameField>
        <label>Reporting Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Months</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Retailed_Vehicles__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_3_Vehicle_Variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 3 Vehicle Variant</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Retailed Vehicles (Level 3 Vehicle Variant)</relationshipLabel>
        <relationshipName>Retailed_Vehicles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Can be -1 for reversals</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Special_Assistance_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Assistance Number</label>
        <referenceTo>Special_Assistance__c</referenceTo>
        <relationshipLabel>Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailed Vehicle</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Retailed Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailed Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Special_Assistance__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Requested_Per_Vehicle__c</fullName>
        <description>Total value across all vehicles of special assistance</description>
        <label>Amount Requested Per Vehicle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Amount_per_Vehicle__c</fullName>
        <label>Approved Amount per Vehicle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <description>Dealer requesting special assistance</description>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Must be a Dealer account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expired Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Special Assistance</relationshipLabel>
        <relationshipName>Special_Assistance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_From_Date__c</fullName>
        <label>Effective From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_To_Date__c</fullName>
        <label>Effective To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Special Assistance</relationshipLabel>
        <relationshipName>Special_Assistance1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Raised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Special Assistance</relationshipLabel>
        <relationshipName>Special_Assistance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicles_Requested__c</fullName>
        <inlineHelpText>Number of vehicles approved by Nissan.</inlineHelpText>
        <label>Number of Vehicles Approved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Special Assistance</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Special Assistance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Assistance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataProvider.cls
@isTest
public class TestDataProvider {
	
	public static Id orgId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organisation').getRecordTypeId();
   	public static Id dealerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();    
   	
	public static List<Contract> createContracts(List<Account> Organisation, List<Product2> products, List<Associated_Product__c> associatedProducts) {
    	List<Contract> contracts = new List<Contract>();
    	for(Integer i = 0; i<15; i++) {
    		contracts.add(new Contract(AccountId = Organisation[i].Id));
    	}
    	for(Integer i=0; i<15; i++) {
    		if(i<10) {
        		Organisation[i].Has_a_Contract__c = true;
        	} else {
        		Organisation[i].ParentId = Organisation[i-1].Id;
        	}
        }
        update Organisation;
        insert contracts;
        for(Contract c : contracts) {
        	c.Status='Active';
        }
        update contracts;
        for(Integer i = 0; i<15; i++) {
    		products.add(new Product2(Name = 'Test a Product'));
    	}
		insert products;
		for(Integer i = 0; i<15; i++) {
    		associatedProducts.add(new Associated_Product__c(Product__c = products[i].Id, Contract__c = contracts[i].Id));
    	}
        insert associatedProducts;
		
		for(Integer i=1; i<15; i++) {
			Organisation[i].ParentId = Organisation[i-1].Id;
        }
        
        update Organisation;
        return contracts;
    }
    
    public static List<Special_Assistance__c> createSpecialAssistance(Integer n, List<Account> Organisation) {
        List<Account> dealers = new List<Account>();
        
        List<Special_Assistance__c> sas = new List<Special_Assistance__c>();
        for(Integer i=0; i<n; i++) {
            dealers.add(new Account(Name='Dealer'+i, RecordTypeId = dealerId));
        }
        insert dealers;
        for(Integer i=0; i<n; i++) {
            Organisation.add(new Account(Name='Org'+i, RecordTypeId = orgId));
        }
        insert Organisation;
        for(Integer i=0; i<n; i++) {
            Special_Assistance__c sa = new Special_Assistance__c(Effective_From_Date__c = system.today(), 
                                                                 Effective_To_Date__c = system.today().addDays(20), 
                                                                 Amount_Requested_Per_Vehicle__c = 100,
                                                                 Approved_Amount_per_Vehicle__c = 100,
                                                                 Approved_Date__c = system.today(),
                                                                 Vehicles_Requested__c = 100,
                                                                 Dealer__c = dealers[i].Id,
                                                                 Status__c = 'Approved',
                                                                 Organisation__c = Organisation[i].Id);
            sas.add(sa);
        }
        insert sas;
        return sas;
    }
    
    public static List<Retailed_Vehicles__c> createRetailedVehicles(List<Special_Assistance__c> sas, List<Account> Organisation, List<Product2> products) {
        List<Retailed_Vehicles__c> rvs = new List<Retailed_Vehicles__c>();
        for(Special_Assistance__c sa : sas) {
            for(Integer i=0; i<15;i++) {
                Retailed_Vehicles__c rv = new Retailed_Vehicles__c(Special_Assistance_Number__c = sa.Id, Quantity__c = 1);
                rvs.add(rv);
            }
        }
        Special_Assistance__c sa = sas[0];
        for(Integer i=0;i<200;i++){
        	Retailed_Vehicles__c rv;
        	if(Math.mod(i,2)==0)
        		rv = new Retailed_Vehicles__c(Special_Assistance_Number__c = sa.Id, Quantity__c = 1, Organisation__c = Organisation[Math.mod(i,15)].Id, Level_3_Vehicle_Variant__c = products[Math.mod(i,15)].Id, Vehicle__c = products[Math.mod(i,15)].Id);
        	else
        		rv = new Retailed_Vehicles__c(Special_Assistance_Number__c = sa.Id, Quantity__c = -1, Organisation__c = Organisation[Math.mod(i,15)].Id, Level_3_Vehicle_Variant__c = products[Math.mod(i,15)].Id, Vehicle__c = products[Math.mod(i,15)].Id);
    		rvs.add(rv);
        }
        if(rvs.size()>0) {
            insert rvs;
        }
		return rvs;
    }
    
    public static List<Account> createAccounts(String name, integer count){
		List<Account> lstAccount = new List<Account>();
		 
		for(integer i =0; i < count; i++){
			Account acct = new Account();
			acct.Name = name;
			lstAccount.add(acct);
		}
		return lstAccount;
    }

    public static List<Opportunity> createOpportunities(String name, String stageName, List<Account> lstAccount, integer count){
		
		List<Opportunity> lstOpportunity = new List<Opportunity>();
		 
		for(integer i =0; i < count; i++){
			Opportunity oppty = new Opportunity();
			oppty.Name = name;
			oppty.CloseDate =  system.today();
			oppty.StageName = stageName;
			oppty.AccountId = lstAccount[Math.mod(i,testOpportunity.accountCount)].id;
			lstOpportunity.add(oppty);
		}
		return lstOpportunity;
    }
    
    public static List<Reporting_Month__c> createReportingMonths(String name , integer count){
		
		List<Reporting_Month__c> lstReportingMonth = new List<Reporting_Month__c>();
		 
		for(integer i =0; i < count; i++){
			Reporting_Month__c reportingMonth = new Reporting_Month__c();
			reportingMonth.Name = name + i;
			lstReportingMonth.add(reportingMonth);
		}
		return lstReportingMonth;
    }
	
	public static List<Delivery_Schedule__c> createDeliverySchedules(List<Reporting_Month__c> reportingMonths, List<Opportunity> lstOpporty , integer count){
		
		List<Delivery_Schedule__c> lstDeliverySchedules = new List<Delivery_Schedule__c>();
		 
		for(integer i =0; i < count; i++){
			Delivery_Schedule__c deliverySchedules = new Delivery_Schedule__c();
			deliverySchedules.Opportunity__c = lstOpporty[Math.mod(i,testOpportunity.opportunityCount)].id;
			deliverySchedules.Report_Month__c = reportingMonths[Math.mod(i,testOpportunity.deliveryScheduleCount)].id;
			lstDeliverySchedules.add(deliverySchedules);
		}
		return lstDeliverySchedules;
    }       
}