src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Status__c</fullName>
        <label>Booking Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Evaluation_Vehicle__c</fullName>
        <label>Evaluation Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Evaluation vehicle with Live status</errorMessage>
            <filterItems>
                <field>Evaluation_Vehicle__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Grounded</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Evaluation_Vehicle__c</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Confirmed_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Confirmed Cancellation</label>
        <type>Checkbox</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Vehicle__c.object
<CustomObject>
    <label>Evaluation Vehicle</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SFDC_Product_Level__c</fullName>
        <inlineHelpText>Indicated which level in the product hierarchy this product sit</inlineHelpText>
        <label>SFDC Product Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/BookingCancellationControllerTest.cls
@isTest(SeeAllData=true)
private class BookingCancellationControllerTest {
	
	static testmethod void cancellationTest1(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
		insert contacts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
		insert evalVehicles;
		
		List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(12,evalVehicles,contacts);
		insert evalBookings;
		
		Test.startTest();
			Test.setCurrentPageReference(new PageReference('Page.BookingCancellation'));
			System.currentPageReference().getParameters().put('bookingId', evalBookings.get(0).Id);
			BookingCancellationController bookingCancellation = new BookingCancellationController();
		Test.stopTest();
	}
	
	static testmethod void cancellationTest2(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
		insert contacts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
		insert evalVehicles;
		
		List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(1,evalVehicles,contacts);
		insert evalBookings;
		
		Test.startTest();
			Test.setCurrentPageReference(new PageReference('Page.BookingCancellation'));
			System.currentPageReference().getParameters().put('bookingId', evalBookings.get(0).Id);
			BookingCancellationController bookingCancellation = new BookingCancellationController();
			bookingCancellation.stillBooked();
			
			System.assertEquals(bookingCancellation.isConfirmationCompleted,false);
			System.assertEquals(bookingCancellation.isForConfirmation,false);
			System.assertEquals(bookingCancellation.isBookingPending,true);
			
		Test.stopTest();
	}
	
	static testmethod void cancellationTest3(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
		insert contacts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
		insert evalVehicles;
		
		List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(1,evalVehicles,contacts);
		insert evalBookings;
		
		Test.startTest();
			Test.setCurrentPageReference(new PageReference('Page.BookingCancellation'));
			System.currentPageReference().getParameters().put('bookingId', evalBookings.get(0).Id);
			BookingCancellationController bookingCancellation = new BookingCancellationController();
			bookingCancellation.confirmationCompleted();
			
			System.assertEquals(bookingCancellation.evaluationBooking.Booking_Status__c,'Pending Cancellation');
			System.assertEquals(bookingCancellation.evaluationBooking.Is_Confirmed_Cancellation__c,true);
			System.assertEquals(bookingCancellation.isConfirmationCompleted,true);
			System.assertEquals(bookingCancellation.isForConfirmation,false);
			
		Test.stopTest();
	}
	
	static testmethod void cancellationTest4(){
		
		List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
		insert accounts;
		
		List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
		insert contacts;
		
		Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
		
		List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
		insert evalVehicles;
		
		List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(12,evalVehicles,contacts);
		evalBookings.get(0).Booking_Status__c = 'Cancelled';
		insert evalBookings;
		
		Test.startTest();
			Test.setCurrentPageReference(new PageReference('Page.BookingCancellation'));
			System.currentPageReference().getParameters().put('bookingId', evalBookings.get(0).Id);
			BookingCancellationController bookingCancellation = new BookingCancellationController();
			
			System.assertEquals(bookingCancellation.isConfirmed,true);
			System.assertEquals(bookingCancellation.isForConfirmation,false);
		Test.stopTest();
	}
}