src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Vehicle__c</fullName>
        <label>Evaluation Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Evaluation vehicle with Live status</errorMessage>
            <filterItems>
                <field>Evaluation_Vehicle__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Grounded</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Evaluation_Vehicle__c</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Confirmation_Sent_Date__c</fullName>
        <label>Survey Confirmation Sent Date</label>
        <type>Date</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Vehicle__c.object
<CustomObject>
    <label>Evaluation Vehicle</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Nissan_Fleet_Vehicles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Nissan Fleet Vehicles</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SFDC_Product_Level__c</fullName>
        <inlineHelpText>Indicated which level in the product hierarchy this product sit</inlineHelpText>
        <label>SFDC Product Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Survey_Result__c.object
<CustomObject>
    <description>Store all the anwers of the booking survey</description>
    <fields>
        <fullName>Evaluation_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation Booking</label>
        <referenceTo>Evaluation_Booking__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_3_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was available when I needed it.</inlineHelpText>
        <label>Vehicle was available when I needed it</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Price</inlineHelpText>
        <label>Price</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyFormControllerTest.cls
@isTest(SeeAllData=true)
private class SurveyFormControllerTest {

	static testmethod void testScenario1(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(12,evalVehicles,contacts);
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			Test.setCurrentPageReference(new PageReference('Page.SurveyForm'));
			System.currentPageReference().getParameters().put('contactId', contacts.get(0).Id);
			System.currentPageReference().getParameters().put('bookingId', evalBookings.get(0).Id);
			
			/*SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.contactId = contacts.get(0).Id;
			surveyForm.bookingId = evalBookings.get(0).Id;*/
			
		Test.stopTest();
	}
	
	static testmethod void testScenario2(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(12,evalVehicles,contacts);
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			List<Nissan_Fleet_Vehicles__c> fleetVehicles = TestDataUtility.createFleetVehicles(3);
			insert fleetVehicles;
			
			/*Test.setCurrentPageReference(new PageReference('Page.SurveyForm'));
			System.currentPageReference().getParameters().put('contactId', contacts.get(0).Id);
			System.currentPageReference().getParameters().put('bookingId', evalBookings.get(0).Id);*/
			
			SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.contactId = contacts.get(0).Id;
			surveyForm.bookingId = evalBookings.get(0).Id;
			
		Test.stopTest();
	}
	
	static testmethod void testScenario3(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(12,evalVehicles,contacts);
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.contactId = contacts.get(0).Id;
			surveyForm.bookingId = evalBookings.get(0).Id;
			surveyForm.question2Value1 = String.valueOf(10);
			surveyForm.question2Value2 = String.valueOf(10);
			surveyForm.question2Value3 = String.valueOf(10);
			surveyForm.question2Value4 = String.valueOf(10);
			surveyForm.question2Value5 = String.valueOf(10);
			surveyForm.question2Value6 = String.valueOf(10);
			surveyForm.question2Value7 = String.valueOf(10);
			surveyForm.question6Value = String.valueOf(10);
			surveyForm.question7Value = String.valueOf(10);
			surveyForm.saveSurvey();
			
		Test.stopTest();
	}
	
	static testmethod void testScenario4(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking2(12,evalVehicles,contacts);
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.contactId = contacts.get(0).Id;
			surveyForm.bookingId = evalBookings.get(0).Id;
			surveyForm.surveyResult.Question_3_1__c = true;
			surveyForm.surveyResult.Question_4_1__c = true;
			surveyForm.question2Value1 = String.valueOf(10);
			surveyForm.question2Value2 = String.valueOf(10);
			surveyForm.question2Value3 = String.valueOf(10);
			surveyForm.question2Value4 = String.valueOf(10);
			surveyForm.question2Value5 = String.valueOf(10);
			surveyForm.question2Value6 = String.valueOf(10);
			surveyForm.question2Value7 = String.valueOf(10);
			surveyForm.question6Value = String.valueOf(10);
			surveyForm.question7Value = String.valueOf(10);
			surveyForm.question8Value = 'Yes';
			surveyForm.saveSurvey();
			
		Test.stopTest();
	}
	
	static testmethod void testScenario5(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking(1,evalVehicles,contacts);
			evalBookings.get(0).Survey_Confirmation_Sent_Date__c = Date.Today();
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.contactId = contacts.get(0).Id;
			surveyForm.bookingId = evalBookings.get(0).Id;
			surveyForm.surveyResult.Question_3_1__c = true;
			surveyForm.surveyResult.Question_4_1__c = true;
			surveyForm.question2Value1 = String.valueOf(10);
			surveyForm.question2Value2 = String.valueOf(10);
			surveyForm.question2Value3 = String.valueOf(10);
			surveyForm.question2Value4 = String.valueOf(10);
			surveyForm.question2Value5 = String.valueOf(10);
			surveyForm.question2Value6 = String.valueOf(10);
			surveyForm.question2Value7 = String.valueOf(10);
			surveyForm.question6Value = String.valueOf(10);
			surveyForm.question7Value = String.valueOf(10);
			surveyForm.question8Value = 'Yes';
			surveyForm.checkExisting();
			surveyForm.saveSurvey();
			
		Test.stopTest();
	}
	
	static testmethod void testScenario6(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking(1,evalVehicles,contacts);
			evalBookings.get(0).Survey_Confirmation_Sent_Date__c = Date.Today();
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.questionNumber = '2-1';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '2-2';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '2-3';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '2-4';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '2-5';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '2-6';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '2-7';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '6-1';
			surveyForm.populateRadios();
			surveyForm.questionNumber = '7-1';
			surveyForm.populateRadios();
			
		Test.stopTest();
	}
	
	static testmethod void testScenario7(){
		Test.startTest();
		
			List<Account> accounts = TestDataUtility.createAccounts(1,'Organisation');
			insert accounts;
			
			List<Contact> contacts = TestDataUtility.createContacts(1,accounts);
			insert contacts;
			
			Product2 vehicle = [Select Id from Product2 where SFDC_Product_Level__c = 1 LIMIT 1];
			
			List<Evaluation_Vehicle__c> evalVehicles = TestDataUtility.createEvaluationVehicle(1,vehicle);
			insert evalVehicles;
			
			List<Evaluation_Booking__c> evalBookings = TestDataUtility.createEvaluationBooking(1,evalVehicles,contacts);
			evalBookings.get(0).Survey_Confirmation_Sent_Date__c = Date.Today();
			insert evalBookings;
			
			List<Survey_Result__c> surveyResults = TestDataUtility.createSurveyResult(1, contacts, evalBookings);
			insert SurveyResults;
			
			SurveyFormController surveyForm = new SurveyFormController();
			surveyForm.contactId = contacts.get(0).Id;
			surveyForm.bookingId = evalBookings.get(0).Id;
			surveyForm.question1Value = 'Better than Current';
			surveyForm.surveyResult.Question_3_1__c = true;
			surveyForm.surveyResult.Question_4_1__c = true;
			surveyForm.question2Value1 = String.valueOf(10);
			surveyForm.question2Value2 = String.valueOf(10);
			surveyForm.question2Value3 = String.valueOf(10);
			surveyForm.question2Value4 = String.valueOf(10);
			surveyForm.question2Value5 = String.valueOf(10);
			surveyForm.question2Value6 = String.valueOf(10);
			surveyForm.question2Value7 = String.valueOf(10);
			surveyForm.question6Value = String.valueOf(10);
			surveyForm.question7Value = String.valueOf(10);
			surveyForm.selectedVehicle = 'TESTVEHICLE';
			surveyForm.question8Value = 'Yes';
			surveyForm.saveSurvey();
			
		Test.stopTest();
	}
}