src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amount_Claimed_by_Organisation__c</fullName>
        <label>Total Amount Claimed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Remaining__c</fullName>
        <label>Amount Remaining</label>
        <summarizedField>Special_Assistance__c.Amount_Remaining__c</summarizedField>
        <summaryFilterItems>
            <field>Special_Assistance__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Special_Assistance__c.Dealer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount_Remaining_by_Organisation__c</fullName>
        <label>Amount Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Requested_by_Organisation__c</fullName>
        <label>Total Approved Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Primary_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organisations</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTS FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEHICLES FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTS &amp; VEHICLE FREEZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CURRENT DEALER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEASED TRADING</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicles_Approved_for_Organisation__c</fullName>
        <label>Number of Vehicles Approved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicles_Claimed_by_Organisation__c</fullName>
        <label>Number of Vehicles Claimed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicles_Remaining_by_Organisation__c</fullName>
        <label>Number of Vehicles remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Nissan Dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Assistance__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Claimed__c</fullName>
        <formula>Vehicles_Claimed__c  *  Approved_Amount_per_Vehicle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Claimed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Remaining__c</fullName>
        <formula>Vehicles_Remaining__c *  Approved_Amount_per_Vehicle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Requested__c</fullName>
        <formula>Vehicles_Requested__c *  Approved_Amount_per_Vehicle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Approved Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Special Assistance</relationshipLabel>
        <relationshipName>Special_Assistance1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Raised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicles_Claimed__c</fullName>
        <inlineHelpText>Number of retailed vehicles against this Special Assistance request.</inlineHelpText>
        <label>Vehicles Claimed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicles_Remaining__c</fullName>
        <formula>Vehicles_Requested__c -  Vehicles_Claimed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicles Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicles_Requested__c</fullName>
        <inlineHelpText>Number of vehicles approved by Nissan.</inlineHelpText>
        <label>Number of Vehicles Approved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Special Assistance</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Special Assistance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Assistance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SpecialAssistanceHelper.cls
public class SpecialAssistanceHelper {

    public static void UpdateOrgs(List<Special_Assistance__c> newSA){
        Set<Id> organisationIds = new Set<Id>();
        Map<Id, Account> toUpdateOrgs = new Map<Id, Account>();
        Map<Id, String> primaryDealerByIds = new Map<Id, String>();
    
        for(Special_Assistance__c sa : newSA) {
            if(sa.Organisation__c!=null && sa.Status__c == 'Approved') {
                organisationIds.add(sa.Organisation__c);
            }
        }
        
        List<Account> dealerAccounts = new List<Account>();
        dealerAccounts = [
                SELECT
                    Id,
                    Primary_Dealer__c,
                    Primary_Dealer__r.RecordType.DeveloperName
                FROM
                    Account
                WHERE
                    Id
                IN
                    :organisationIds
                ];
                
        for(Account account : dealerAccounts){
            System.debug('##RECORDTYPE: '+account.Primary_Dealer__r.RecordType.DeveloperName);
            primaryDealerByIds.put(account.Id, account.Primary_Dealer__r.RecordType.DeveloperName);
        }
    
        for(Special_Assistance__c sa : newSA) {
            if(sa.Organisation__c!=null && sa.Status__c == 'Approved') {
                if(primaryDealerByIds.get(sa.Organisation__c) == 'Dealer'){
                    toUpdateOrgs.put(sa.Organisation__c,new Account());
                }
            }
        }
        
        if(toUpdateOrgs.size()>0) {
            updateAllOrgs(toUpdateOrgs);
        }
    }
    
    public static void UpdateOrgs(List<Special_Assistance__c> oldSA, List<Special_Assistance__c> newSA){
        Set<Id> organisationIds = new Set<Id>();
        Map<Id, Account> toUpdateOrgs = new Map<Id, Account>();
        Map<Id, String> primaryDealerByIds = new Map<Id, String>();
        
        for(Special_Assistance__c sa : newSA) {
            if(sa.Organisation__c!=null && sa.Status__c == 'Approved') {
                organisationIds.add(sa.Organisation__c);
            }
        }
        
        List<Account> dealerAccounts = new List<Account>();
        dealerAccounts = [
                SELECT
                    Id,
                    Primary_Dealer__c,
                    Primary_Dealer__r.RecordType.DeveloperName
                FROM
                    Account
                WHERE
                    Id
                IN
                    :organisationIds
                ];
                
        for(Account account : dealerAccounts){
            System.debug('##RECORDTYPE: '+account.Primary_Dealer__r.RecordType.DeveloperName);
            primaryDealerByIds.put(account.Id, account.Primary_Dealer__r.RecordType.DeveloperName);
        }
    
        for(Integer i=0; i<oldSA.size(); i++) {
            if(primaryDealerByIds.get(newSA[i].Organisation__c) == 'Dealer'){
                if((newSA[i].Status__c != oldSA[i].Status__c) &&
                    ((newSA[i].Organisation__c!=null && newSA[i].Status__c == 'Approved') ||
                    (newSA[i].Organisation__c!=null && oldSA[i].Status__c == 'Approved'))) {
                     toUpdateOrgs.put(newSA[i].Organisation__c,new Account(
                                                                        id=newSA[i].Organisation__c,
                                                                        Amount_Remaining_by_Organisation__c = 0, 
                                                                        Amount_Claimed_by_Organisation__c = 0,
                                                                        Amount_Requested_by_Organisation__c = 0,
                                                                        Vehicles_Approved_for_Organisation__c = 0, 
                                                                        Vehicles_Claimed_by_Organisation__c = 0,
                                                                        Vehicles_Remaining_by_Organisation__c = 0
                                                                    ));
                 }
            }
            
        }
        
        if(toUpdateOrgs.size()>0) {
            updateAllOrgs(toUpdateOrgs);
        }
    }
    
    public static void updateAllOrgs(Map<Id, Account> toUpdateOrgs) {
        for (AggregateResult ar : [Select Organisation__c, SUM(Amount_Claimed__c) amtClaimed, SUM(Amount_Requested__c) amtRequested, SUM(Amount_Remaining__c) amtRemaining,
                                    SUM(Vehicles_Requested__c) vehiclesApproved, SUM(Vehicles_Claimed__c) vehiclesClaimed, 
                                    SUM(Vehicles_Remaining__c) vehiclesRemaining from Special_Assistance__c where 
                                    Status__c = 'Approved' and Organisation__c in :toUpdateOrgs.keyset() group by Organisation__c])  {
            
            Account a = new Account(Id = Id.valueOf(String.valueOf(ar.get('Organisation__c'))),
                                    Amount_Remaining_by_Organisation__c = Integer.valueOf(ar.get('amtRemaining')), 
                                    Amount_Claimed_by_Organisation__c = Integer.valueOf(ar.get('amtClaimed')),
                                    Amount_Requested_by_Organisation__c = Integer.valueOf(ar.get('amtRequested')),
                                    Vehicles_Approved_for_Organisation__c = Integer.valueOf(ar.get('vehiclesApproved')), 
                                    Vehicles_Claimed_by_Organisation__c = Integer.valueOf(ar.get('vehiclesClaimed')),
                                    Vehicles_Remaining_by_Organisation__c = Integer.valueOf(ar.get('vehiclesRemaining')));
            system.debug('ACCOUNT**'+a);
            toUpdateOrgs.put(Id.valueOf(String.valueOf(ar.get('Organisation__c'))),a);
        }
        if(!toUpdateOrgs.isempty()){
            Update toUpdateOrgs.values();   
        }
    }
}