src/objects/Associated_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Associated Products</relationshipLabel>
        <relationshipName>Associated_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Associated Products</relationshipLabel>
        <relationshipName>Associated_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Product</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Retailed_Vehicles__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_3_Vehicle_Variant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 3 Vehicle Variant</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Retailed Vehicles (Level 3 Vehicle Variant)</relationshipLabel>
        <relationshipName>Retailed_Vehicles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Retailed Vehicles</relationshipLabel>
        <relationshipName>Retailed_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retailed Vehicle</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Retailed Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retailed Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AccountHelper.cls
public class AccountHelper {
	
	public static void changeOwnerofAssociatedActiveContracts(List<Account> oldAccounts, List<Account> newAccounts) {
		Map<Id, Id> accountOwnerIdMap = new Map<Id,Id>();
		for(Integer i=0; i<oldAccounts.size(); i++) {
			if(newAccounts[i].OwnerId != oldAccounts[i].OwnerId) {
				accountOwnerIdMap.put(newAccounts[i].Id,newAccounts[i].OwnerId);
			}
		}
		if(accountOwnerIdMap.size()>0) {
			List<Contract> toUpdateContracts = new List<Contract>();
			for(Contract c : [Select AccountId,OwnerId from Contract where AccountId in :accountOwnerIdMap.keyset() and Status = 'Active']) {
				c.OwnerId = accountOwnerIdMap.get(c.AccountId);
				toUpdateContracts.add(c);
			}
			if(toUpdateContracts.size()>0) {
				update toUpdateContracts;
			}
		}
	}
	
	public static void associateContractsForRetailedVehicles(List<Account> oldAccounts, List<Account> newAccounts) {
		Set<Id> accountIds = new Set<Id>();
		Map<Id,Id> accountWithContractIds = new Map<Id, Id>();
		for(Integer i=0; i<oldAccounts.size(); i++) {
			if(newAccounts[i].ParentId != oldAccounts[i].ParentId) {
				accountIds.add(newAccounts[i].Id);
			}
		}
		accountWithContractIds = RetailedVehiclesHelper.getParentAccounts(accountIds);
		Map<Id,Id> ProductAndContractIds = new Map<Id,Id>();
		for(Associated_Product__c ap : [Select Id, Product__c, Contract__r.Id, Contract__c, Contract__r.AccountId from Associated_Product__c where Contract__r.AccountId in :accountWithContractIds.keyset() and Contract__r.Status = 'Active']) {
			ProductAndContractIds.put(ap.Product__c,ap.Contract__r.Id);
    	}
    	system.debug('--PRODUCT WITH CONTRACTS'+ProductAndContractIds);
    	List<Retailed_Vehicles__c> toUpdate = new List<Retailed_Vehicles__c>();
    	for(Retailed_Vehicles__c rv : [Select Id, Level_3_Vehicle_Variant__c from Retailed_Vehicles__c where Organisation__c in :accountIds and Level_3_Vehicle_Variant__c in :ProductAndContractIds.keyset()]) {
            rv.Contract__c = ProductAndContractIds.get(rv.Level_3_Vehicle_Variant__c);
            toUpdate.add(rv);
	    }
	    if(toUpdate.size()>0) {
	    	update toUpdate;
	    }
	}

}