src/objects/Delivery_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Delivery Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityManager.cls
public class OpportunityManager {
	
	public static void removeDeliverySchedules(List<Opportunity> lstNewOppty,List<Opportunity> lstOldOppty){
		
		//Set Opportunity ids
		set<id> setOpptyIds = new set<id>();
		 
		for(Integer i =0; i < lstNewOppty.size(); i++){
			if((lstNewOppty[i].StageName != lstOldOppty[i].StageName ) && (lstNewOppty[i].StageName == 'Closed Lost' || lstNewOppty[i].StageName == 'Discontinued')){
				setOpptyIds.add(lstNewOppty[i].id);
			}
		}
		if(!setOpptyIds.isempty()){
			OpportunityManager.deleteDeliverySchedules(setOpptyIds);
		}
	}
	
	public static void deleteDeliverySchedules(set<id> setOpptyIds){
		delete([SELECT id FROM Delivery_Schedule__c WHERE Opportunity__c IN:setOpptyIds]);
	}
}