src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Status__c</fullName>
        <label>Booking Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Confirmed_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Confirmed Cancellation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_Name__c</fullName>
        <formula>Evaluation_Vehicle__r.Vehicle__r.Name</formula>
        <label>Vehicle Name</label>
        <type>Text</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BookingCancellationController.cls
public with sharing class BookingCancellationController {

	public Evaluation_Booking__c evaluationBooking {get;set;}
	public String bookingId {get;set;}
	public Boolean isForConfirmation {get;set;}
	public Boolean isConfirmationCompleted {get;set;}
	public Boolean isConfirmed {get;set;}
	public Boolean isBookingPending {get;set;}
	public String startDate {get;set;}
	public String endDate {get;set;}
	
	public BookingCancellationController(){
		evaluationBooking = new Evaluation_Booking__c();
		bookingId = ApexPages.currentPage().getParameters().get('bookingId');
		isForConfirmation = true;
		isConfirmed = false;
		isBookingPending = false;
		isConfirmationCompleted = false;
		checkIfConfirmed();
	}
	
	public void checkIfConfirmed(){
		if(bookingId != ''){
			evaluationBooking = [SELECT Id, Booking_Status__c, Is_Confirmed_Cancellation__c, Vehicle_Name__c, Start_Date__c, End_Date__c FROM Evaluation_Booking__c where Id = :bookingId];
			startDate = evaluationBooking.Start_Date__c.format();
			endDate = evaluationBooking.End_Date__c.format();
			if(evaluationBooking.Booking_Status__c == 'Pending Cancellation' || evaluationBooking.Booking_Status__c == 'Cancelled'){
				isForConfirmation = false;
				isConfirmed = true;
			}
		}
	}
	
	public void stillBooked(){
		isForConfirmation = false;
		isConfirmed = false;
		isBookingPending = true;
		
	}
	
	public void confirmationCompleted(){
		isConfirmationCompleted = true;
		isForConfirmation = false;
		evaluationBooking.Booking_Status__c = 'Pending Cancellation';
		evaluationBooking.Is_Confirmed_Cancellation__c = true;
		update evaluationBooking;
	}
}