src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Confirmation_Sent_Date__c</fullName>
        <label>Booking Confirmation Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Booking_Confirmation_Status__c</fullName>
        <label>Booking Confirmation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Booking_Confirmation_to_be_sent__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Booking Confirmation to be sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter a Contact with a valid email</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_By_Email__c</fullName>
        <formula>IF(OR(ISNULL(Nissan_Representative__r.Email),ISBLANK(Nissan_Representative__r.Email)),
   &apos;&apos;,
   Nissan_Representative__r.Email)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created By Email</label>
        <type>Text</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendConfirmationEmailExtension.cls
/**
    *This is a controller class of the SendConfirmationEmail page
    *@author Kengo Chinen - Proquest IT
    *@version 1.0 Created 10/15/2014
**/
public with sharing class SendConfirmationEmailExtension {

    ApexPages.StandardController controller;
    private final Evaluation_Booking__c evaluationBooking;

    public SendConfirmationEmailExtension(ApexPages.StandardController controller) {
        this.controller = controller;
        evaluationBooking = [SELECT Id, Contact__c, Booking_Confirmation_Status__c, Booking_Confirmation_Sent_Date__c, Created_By_Email__c FROM Evaluation_Booking__c WHERE Id =:controller.getId()];
    }

    public PageReference sendEmail() {
        
        List<String> ccRecipients = new List<String>();
        ccRecipients.add(evaluationBooking.Created_By_Email__c);
        
        String contactId = evaluationBooking.Contact__c;
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTemplateId('00XN0000000MCdf'); //Template in Dev
        message.setCCAddresses(ccRecipients);
        message.setTargetObjectId(contactId);
        message.setWhatId(evaluationBooking.Id);
        message.setSaveAsActivity(true);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
        
        evaluationBooking.Booking_Confirmation_Status__c = 'Sent';
        evaluationBooking.Booking_Confirmation_Sent_Date__c = Date.Today();
        evaluationBooking.Booking_Confirmation_to_be_sent__c = false;
        
        update evaluationBooking;
        
        return controller.view();
       
    }

}