src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter a Contact with a valid email</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Confirmation_Sent_Date__c</fullName>
        <label>Survey Confirmation Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Confirmation_Status__c</fullName>
        <label>Survey Confirmation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_to_be_Sent__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Survey to be Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendSurveyEmailExtension.cls
/**
    *This is a controller extension class of the SendSurveyEmail page
    *@author Kim Noceda - Proquest IT
    *@version 1.0 Created 10/16/2014
**/
public with sharing class SendSurveyEmailExtension {

	ApexPages.StandardController controller;
    private final Evaluation_Booking__c evaluationBooking;

    public SendSurveyEmailExtension(ApexPages.StandardController controller) {
        this.controller = controller;
        evaluationBooking = [SELECT Id, Contact__c, Survey_Confirmation_Status__c, Survey_Confirmation_Sent_Date__c FROM Evaluation_Booking__c WHERE Id =:controller.getId()];
    }

    public PageReference sendEmail() {
        
        String contactId = evaluationBooking.Contact__c;
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTemplateId('00XN0000000MCgP'); //Template in Dev
        message.setTargetObjectId(contactId);
        message.setWhatId(evaluationBooking.Id);
        message.setSaveAsActivity(true);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
        
        evaluationBooking.Survey_Confirmation_Status__c = 'Sent';
        evaluationBooking.Survey_Confirmation_Sent_Date__c = Date.Today();
        evaluationBooking.Survey_to_be_Sent__c = false;
        
        update evaluationBooking;
        
        return controller.view();
       
    }
}