src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation_Vehicle__c</fullName>
        <label>Evaluation Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Evaluation vehicle with Live status</errorMessage>
            <filterItems>
                <field>Evaluation_Vehicle__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Grounded</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Evaluation_Vehicle__c</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Vehicle__c.object
<CustomObject>
    <label>Evaluation Vehicle</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EvaluationBookingTriggerHandler.cls
/**
    *This is a trigger handler class for the EvaluationVehicleTrigger
    *@author Kim Noceda - Proquest IT
    *@version 1.0 Created 10/13/2014
**/
public with sharing class EvaluationBookingTriggerHandler {

    public static void validateBookingDates(List<Evaluation_Booking__c> evaluationBookings){
        
        Set<Id> evalVehiclesIds = new Set<Id>();
        Set<Id> newBookingIds = new Set<Id>();
        for(Evaluation_Booking__c bookings : evaluationBookings){
            evalVehiclesIds.add(bookings.Evaluation_Vehicle__c);
            newBookingIds.add(bookings.Id);
        }
        
        List<Evaluation_Booking__c> evalBookings = [
                                    SELECT
                                        Id,
                                        Evaluation_Vehicle__c,
                                        Start_Date__c,
                                        End_Date__c
                                    FROM
                                        Evaluation_Booking__c
                                    WHERE
                                        Evaluation_Vehicle__c
                                    IN
                                        :evalVehiclesIds
                                    AND
                                        Id
                                    NOT IN
                                        :newBookingIds
                                    ];
                                    
        for(Evaluation_Booking__c bookings : evaluationBookings){
            for(Evaluation_Booking__c evalBooking : evalBookings){
                if(((bookings.Start_Date__c >= evalBooking.Start_Date__c && bookings.Start_Date__c <= evalBooking.End_Date__c) || (bookings.End_Date__c >= evalBooking.Start_Date__c && bookings.Start_Date__c <= evalBooking.Start_Date__c)) && bookings.Evaluation_Vehicle__c == evalBooking.Evaluation_Vehicle__c){
                   bookings.addError('There is already a booking on these dates for the corresponding Evaluation Vehicle');
                }
            }
        }
    }
}