src/objects/Evaluation_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter a Contact with a valid email</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_By_Email__c</fullName>
        <formula>IF(OR(ISNULL(Nissan_Representative__r.Email),ISBLANK(Nissan_Representative__r.Email)),
   &apos;&apos;,
   Nissan_Representative__r.Email)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created By Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Name__c</fullName>
        <formula>IF(OR(ISNULL(Nissan_Representative__r.FirstName),ISBLANK(Nissan_Representative__r.FirstName)),
   Nissan_Representative__r.LastName, 
   Nissan_Representative__r.FirstName+&apos; &apos;+Nissan_Representative__r.LastName)</formula>
        <label>Created By Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Phone__c</fullName>
        <formula>IF(NOT(ISBLANK(Nissan_Representative__r.MobilePhone)),
   Nissan_Representative__r.MobilePhone,
   Nissan_Representative__r.Phone)</formula>
        <label>Created By Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Evaluation_Vehicle__c</fullName>
        <label>Evaluation Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Evaluation vehicle with Live status</errorMessage>
            <filterItems>
                <field>Evaluation_Vehicle__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Grounded</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Evaluation_Vehicle__c</referenceTo>
        <relationshipLabel>Evaluation Bookings</relationshipLabel>
        <relationshipName>Evaluation_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Model__c+&quot; - &quot;+ Evaluation_Vehicle__r.Vehicle__r.Name</formula>
        <label>Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <label>Organisation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Evaluation_Vehicle__r.Status__c )</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Confirmation_Sent_Date__c</fullName>
        <label>Survey Confirmation Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Form_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Survey Form Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Name__c</fullName>
        <formula>Evaluation_Vehicle__r.Vehicle__r.Name</formula>
        <label>Vehicle Name</label>
        <type>Text</type>
    </fields>
    <label>Evaluation Booking</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Evaluation Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Model__c + &quot; - &quot; + Vehicle__r.Name</formula>
        <label>Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Evaluation Vehicles</relationshipLabel>
        <relationshipName>Evaluation_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grounded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grounded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select vehicles with SFDC Product Level 1</errorMessage>
            <filterItems>
                <field>Product2.SFDC_Product_Level__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Evaluation Vehicles</relationshipLabel>
        <relationshipName>Evaluation_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation Vehicle</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Model_Series__c</fullName>
        <label>Model Series</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Product_Level__c</fullName>
        <inlineHelpText>Indicated which level in the product hierarchy this product sit</inlineHelpText>
        <label>SFDC Product Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Survey_Result__c.object
<CustomObject>
    <description>Store all the anwers of the booking survey</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluation_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation Booking</label>
        <referenceTo>Evaluation_Booking__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <description>How would you rate this vehicle compared to your current like for like fleet/drive vehicle?</description>
        <inlineHelpText>How would you rate this vehicle compared to your current like for like fleet/drive vehicle?</inlineHelpText>
        <label>Vehicle rate compared to current vehicle</label>
        <picklist>
            <picklistValues>
                <fullName>Better than current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Same as current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worse than current</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_3_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was available when I needed it.</inlineHelpText>
        <label>Vehicle was available when I needed it</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was available for as long as I needed it</inlineHelpText>
        <label>Available for as long as you needed it</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was vehicle delivered by a Nissan representative</inlineHelpText>
        <label>Delivered by a Nissan representative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was delivered by a transport supplier</inlineHelpText>
        <label>Delivered by a transport supplier</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_5__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was vehicle delivered clean</inlineHelpText>
        <label>Vehicle delivered clean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_6__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>The vehicle was delivered with suitable fuel</inlineHelpText>
        <label>Delivered with suitable fuel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_7__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>I was advised of the insurance and tolls policy for driving this vehicle</inlineHelpText>
        <label>Advised of Insurance and Tolls policy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_3_8__c</fullName>
        <defaultValue>false</defaultValue>
        <description>How would you rate your overall vehicle evaluation experience? (Tick applicable)</description>
        <inlineHelpText>I signed the Indemnity Form</inlineHelpText>
        <label>I signed the Indemnity Form</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Price</inlineHelpText>
        <label>Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Fit for Purpose</inlineHelpText>
        <label>Fit for Purpose</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Whole of Life costs</inlineHelpText>
        <label>Whole of Life costs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Accessories</inlineHelpText>
        <label>Accessories</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_5__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Warranty</inlineHelpText>
        <label>Warranty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_4_6__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Would there be any barriers to purchasing this vehicle? (Tick applicable)</description>
        <inlineHelpText>Other</inlineHelpText>
        <label>Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_8__c</fullName>
        <description>Would you like to stay updated with Nissan Fleet news?</description>
        <inlineHelpText>Would you like to stay updated with Nissan Fleet news?</inlineHelpText>
        <label>Stay updated with Nissan Fleet news?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyFormController.cls
/**
    *This is a controller class of the SurveyForm page
    *@author Kim Noceda - Proquest IT
    *@version 1.0 Created 10/16/2014
**/
public with sharing class SurveyFormController {
	
	//LABELS
	public String question_1 {get;set;}
	public String question_1Comment {get;set;}
	public String question_2 {get;set;}
	public String question_2_1 {get;set;}
	public String question_2_2 {get;set;}
	public String question_2_3 {get;set;}
	public String question_2_4 {get;set;}
	public String question_2_5 {get;set;}
	public String question_2_6 {get;set;}
	public String question_2_7 {get;set;}
	public String question_3 {get;set;}
	public String question_3_1 {get;set;}
	public String question_3_2 {get;set;}
	public String question_3_3 {get;set;}
	public String question_3_4 {get;set;}
	public String question_3_5 {get;set;}
	public String question_3_6 {get;set;}
	public String question_3_7 {get;set;}
	public String question_3_8 {get;set;}
	public String question_3Comment {get;set;}
	public String question_4 {get;set;}
	public String question_4_1 {get;set;}
	public String question_4_2 {get;set;}
	public String question_4_3 {get;set;}
	public String question_4_4 {get;set;}
	public String question_4_5 {get;set;}
	public String question_4_6 {get;set;}
	public String question_4Comment {get;set;}
	public String question_5 {get;set;}
	public String question_6 {get;set;}
	public String question_7 {get;set;}
	public String question_8 {get;set;}
	
	//VARIABLES
	public Survey_Result__c surveyResult {get;set;}
	public Evaluation_Booking__c evaluationBooking {get;set;}
	public String contactId {get;set;}
	public String bookingId {get;set;}
	public String question1Value {get;set;}
	public String question1CommentValue {get;set;}
	public String question2Value1 {get;set;}
	public String question2Value2 {get;set;}
	public String question2Value3 {get;set;}
	public String question2Value4 {get;set;}
	public String question2Value5 {get;set;}
	public String question2Value6 {get;set;}
	public String question2Value7 {get;set;}
	public String selectedVehicle {get;set;}
	public String question6Value {get;set;}
	public String question7Value {get;set;}
	public String question8Value {get;set;}
	public List<SelectOption> q1Picklist {get; set;}
	public List<SelectOption> q2Picklist {get; set;}
	public List<SelectOption> q5Picklist {get; set;}
	public List<SelectOption> q8Picklist {get; set;}
	public Boolean isValidSurvey {get;set;}
	public Boolean isCompleted {get;set;}
	public Boolean isExisting {get;set;}
	public List<Survey_Result__c> surveyResultList = new List<Survey_Result__c>();
	public String formattedSurveyDate {get;set;}
	public String questionNumber {get;set;}
	public String answerValue {get;set;}

	public SurveyFormController(){
		surveyResult = new Survey_Result__c();
		evaluationBooking = new Evaluation_Booking__c();
		surveyResultList = new List<Survey_Result__c>();
		formattedSurveyDate = '';
		questionNumber = '';
		answerValue = '';
		isValidSurvey = true;
		isCompleted = false;
		isExisting = false;
		contactId = ApexPages.currentPage().getParameters().get('contactId');
		bookingId = ApexPages.currentPage().getParameters().get('bookingId');
		checkExisting();
		initialiseQuestionLabels();
		question1Value = '';
		question2Value1 = '';
		question2Value2 = '';
		question2Value3 = '';
		question2Value4 = '';
		question2Value5 = '';
		question2Value6 = '';
		question2Value7 = '';
		selectedVehicle = '';
		question6Value = '';
		question7Value = '';
		question8Value = '';
		q1Picklist = getQuestion1Items();
		q2Picklist = getQuestion2Items();
		q5Picklist = getQuestion5Items();
		q8Picklist = getQuestion8Items();
		question1CommentValue = '';
	}
	
	public void populateRadios(){
		if(questionNumber == '2-1'){
			question2Value1 = answerValue;
		}
		if(questionNumber == '2-2'){
			question2Value2 = answerValue;
		}
		if(questionNumber == '2-3'){
			question2Value3 = answerValue;
		}
		if(questionNumber == '2-4'){
			question2Value4 = answerValue;
		}
		if(questionNumber == '2-5'){
			question2Value5 = answerValue;
		}
		if(questionNumber == '2-6'){
			question2Value6 = answerValue;
		}
		if(questionNumber == '2-7'){
			question2Value7 = answerValue;
		}
		if(questionNumber == '6-1'){
			question6Value = answerValue;
		}
		if(questionNumber == '7-1'){
			question7Value = answerValue;
		}
		system.debug('@@QUESTION1: '+question1Value);
		system.debug('@@QUESTION2-1: '+question2Value1);
		system.debug('@@QUESTION2-2: '+question2Value2);
		system.debug('@@QUESTION2-3: '+question2Value3);
		system.debug('@@QUESTION2-4: '+question2Value4);
		system.debug('@@QUESTION2-5: '+question2Value5);
		system.debug('@@QUESTION2-6: '+question2Value6);
		system.debug('@@QUESTION2-7: '+question2Value7);
		system.debug('@@QUESTION6-1: '+question6Value);
		system.debug('@@QUESTION7-1: '+question7Value);
		system.debug('@@QUESTION8: '+question8Value);
	}
	
	public void checkExisting(){
		if(bookingId != null && contactId != null){
			evaluationBooking = [SELECT Id, Model_Name__c, Organisation__c, Created_By_Name__c, Created_By_Email__c, Created_By_Phone__c, Survey_Confirmation_Sent_Date__c, Contact__r.Name, Evaluation_Vehicle__r.Vehicle__c, Survey_Form_Completed__c, Vehicle_Name__c FROM Evaluation_Booking__c WHERE Contact__c =:contactId AND Id =: bookingId LIMIT 1];
			formattedSurveyDate = evaluationBooking.Survey_Confirmation_Sent_Date__c.format();
			if(evaluationBooking != null){
				surveyResultList = [SELECT Id, Contact__c, Evaluation_Booking__c from Survey_Result__c WHERE Contact__c =:contactId AND Evaluation_Booking__c =: bookingId];
				if(surveyResultList.size() > 0){
					isValidSurvey = false;
					isExisting = true;
				}
			}
		}
	}
	
	public list<SelectOption> getQuestion1Items(){
	    List<SelectOption> q1Picklist = new List<SelectOption>();
		Schema.DescribeFieldResult fieldResult = Survey_Result__c.Question_1__c.getDescribe();
   		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
	    for( Schema.PicklistEntry f : ple){
	      q1Picklist.add(new SelectOption(f.getLabel(), f.getValue()));
	   	}   
	   	return q1Picklist; 
	}
	
	public list<SelectOption> getQuestion2Items(){
		List<SelectOption> q2Picklist = new List<SelectOption>();
		for(integer i=1;i<=10;i++){
			q2Picklist.add(new SelectOption(String.valueOf(i),String.valueOf(i)));
		}
		return q2Picklist;
	}
	
	public list<SelectOption> getQuestion8Items(){
	    List<SelectOption> q8Picklist = new List<SelectOption>();
		Schema.DescribeFieldResult fieldResult = Survey_Result__c.Question_8__c.getDescribe();
   		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
	    for( Schema.PicklistEntry f : ple){
	      q8Picklist.add(new SelectOption(f.getLabel(), f.getValue()));
	   	}   
	   	return q8Picklist; 
	}
	
	public list<SelectOption> getQuestion5Items(){
		List<SelectOption> q5Picklist = new List<SelectOption>();
		/*List<Product2> vehicles = [SELECT Id, Name, Model_Series__c FROM Product2 WHERE SFDC_Product_Level__c = 1];
		for(Product2 product : vehicles){
			String modelName = product.Model_Series__c+' - '+product.Name;
			q5Picklist.add(new SelectOption(modelName,modelName));
		}
		List<Evaluation_Vehicle__c> vehicles = [SELECT Id, Name, Model_Name__c FROM Evaluation_Vehicle__c Where Status__c <> 'Grounded'];
		for(Evaluation_Vehicle__c vehicle : vehicles){
			q5Picklist.add(new SelectOption(vehicle.Model_Name__c,vehicle.Model_Name__c));
		}*/
		List<Nissan_Fleet_Vehicles__c> fleetVehicles = [SELECT Name FROM Nissan_Fleet_Vehicles__c ORDER BY Name ASC];
		for(Nissan_Fleet_Vehicles__c fleetVehicle : fleetVehicles){
			q5Picklist.add(new SelectOption(fleetVehicle.Name,fleetVehicle.Name));
		}
		return q5Picklist;
	}
	
	public void initialiseQuestionLabels(){
		question_1 = 'How would you rate this vehicle compared to your current like for like fleet/drive vehicle?';  
	    question_1Comment = 'Comments';  
	    question_2 = 'Please rate the vehicle from 0-10 in the following key areas';  
	    question_2_1 = 'Performance (engine options and fuel economy)';  
	    question_2_2 = 'Safety (safety technology)';  
	    question_2_3 = 'Comfort and Handling (seat position/adjustability, visibility, road handling)';  
	    question_2_4 = 'Styling (interior and exterior)';  
	    question_2_5 = 'Innovation (vehicle features and specification)';  
	    question_2_6 = 'Fit for Purpose (specific needs e.g. storage, flexibility)';  
	    question_2_7 = 'Value for Money (includes price of vehicle, servicing costs and Whole of Life calculation)';
	    question_3 = 'How would you rate your overall vehicle evaluation experience? (Tick applicable)';
	    question_3_1 = 'The vehicle was available when I needed it';  
	    question_3_2 = 'The vehicle was available for as long as I needed it';  
	    question_3_3 = 'The vehicle was vehicle delivered by a Nissan representative';  
	    question_3_4 = 'The vehicle was delivered by a transport supplier';  
	    question_3_5 = 'The vehicle was vehicle delivered clean';  
	    question_3_6 = 'The vehicle was delivered with suitable fuel';  
	    question_3_7 = 'I was advised of the insurance and tolls policy for driving this vehicle';  
	    question_3_8 = 'I signed the Indemnity Form';  
	    question_3Comment = 'Comments';  
	    question_4 = 'Would there be any barriers to purchasing this vehicle? (Tick applicable)';
	    question_4_1 = 'Price';  
	    question_4_2 = 'Fit for Purpose';  
	    question_4_3 = 'Whole of Life costs';  
	    question_4_4 = 'Accessories';  
	    question_4_5 = 'Warranty';  
	    question_4_6 = 'Other';  
	    question_4Comment = 'Comments';  
	    question_5 = 'What Nissan vehicle would you like to drive next?';  
	    question_6 = 'Based on your experience with Nissan Fleet, how likely are you to recommend Nissan to a friend or colleague?';  
	    question_7 = 'Based on your experience with driving the '+evaluationBooking.Model_Name__c+', how likely are you to recommend this vehicle to a friend or colleague?';  
	    question_8 = 'Would you like to stay updated with Nissan Fleet news?'; 
	}
	
	public void saveSurvey(){
		Boolean isError = false;
		if(question1Value == ''){
			system.debug('^^1');
			isError = true;
		}
		if(question2Value1 == '' || question2Value2 == '' || question2Value3 == '' || question2Value4 == '' ||
			question2Value5 == '' || question2Value6 == '' || question2Value7 == ''){
			system.debug('^^2');
			isError = true;
		}
		if(surveyResult.Question_3_1__c == false && surveyResult.Question_3_2__c == false && surveyResult.Question_3_3__c == false &&
			surveyResult.Question_3_4__c == false && surveyResult.Question_3_5__c == false && surveyResult.Question_3_6__c == false &&
			surveyResult.Question_3_7__c == false && surveyResult.Question_3_8__c == false){
			system.debug('^^3');
			isError = true;
		}
		if(surveyResult.Question_4_1__c == false && surveyResult.Question_4_2__c == false && surveyResult.Question_4_3__c == false &&
			surveyResult.Question_4_4__c == false && surveyResult.Question_4_5__c == false && surveyResult.Question_4_6__c == false){
			system.debug('^^4');
			isError = true;
		}
		if(selectedVehicle == ''){
			system.debug('^^5');
			isError = true;
		}
		if(question6Value == ''){
			system.debug('^^6');
			isError = true;
		}
		if(question7Value == ''){
			system.debug('^^7');
			isError = true;
		}
		if(question8Value == ''){
			system.debug('^^8');
			isError = true;
		}
		
		if(isError == true){
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'All questions are mandatory. Please answer all questions before submitting the survey form.');
    		ApexPages.addMessage(myMsg);
		} else {
			surveyResult.Question_1__c = question1Value;
			system.debug('$$'+question2Value1);
			if(question2Value1 != ''){
				surveyResult.Question_2_1__c = Integer.valueOf(question2Value1);
			}
			if(question2Value2 != ''){
				surveyResult.Question_2_2__c = Integer.valueOf(question2Value2);
			}
			if(question2Value3 != ''){
				surveyResult.Question_2_3__c = Integer.valueOf(question2Value3);
			}
			if(question2Value4 != ''){
				surveyResult.Question_2_4__c = Integer.valueOf(question2Value4);
			}
			if(question2Value5 != ''){
				surveyResult.Question_2_5__c = Integer.valueOf(question2Value5);
			}
			if(question2Value6 != ''){
				surveyResult.Question_2_6__c = Integer.valueOf(question2Value6);
			}
			if(question2Value7 != ''){
				surveyResult.Question_2_7__c = Integer.valueOf(question2Value7);
			}
			surveyResult.Question_5__c = selectedVehicle;
			if(question6Value != ''){
				surveyResult.Question_6__c = Integer.valueOf(question6Value);
			}
			if(question7Value != ''){
				surveyResult.Question_7__c = Integer.valueOf(question7Value);
			}
			surveyResult.Question_8__c = question8Value;
			surveyResult.Contact__c = contactId;
			surveyResult.Evaluation_Booking__c = bookingId;
			surveyResult.Vehicle__c = evaluationBooking.Evaluation_Vehicle__r.Vehicle__c;
			
			insert surveyResult;
			
			evaluationBooking.Survey_Form_Completed__c = true;
			update evaluationBooking;
			
			isValidSurvey = false;
			isCompleted = true;
		}
	}
}